<?php

namespace ACore\Components\CharactersMenu;

/**
 * PHP port of AzerothCore's PlayerDumpWriter (PlayerDump.cpp).
 *
 * Produces a dump string identical in format to the one generated by the
 * in-game / console `pdump write` command, with all PII automatically stripped.
 *
 * PII stripping applied:
 *  - characters: money, logout_time, totaltime, leveltime, latency, online,
 *                creation_date, death_expire_time, rest_bonus, is_logout_resting,
 *                todayHonorPoints, yesterdayHonorPoints, todayKills, yesterdayKills,
 *                taxi_path, innTriggerId, trans_x/y/z/o/transguid zeroed/nulled.
 *                Position, map, zone, orientation → faction capital city.
 *  - character_homebind: reset to same faction capital city.
 *  - mail: subject + body → 'Redacted'.
 *  - character_pet: name → empty (game uses default name on load).
 *  - character_declinedname, character_pet_declinedname: skipped entirely.
 *  - character_account_data: time zeroed; type-7 blob has custom channel names stripped.
 *  - item_instance: playedTime zeroed; text nulled; creatorGuid + giftCreatorGuid zeroed.
 *
 * Usage:
 *   $writer = new CharacterDumpWriter($characterDbConnection);
 *   $dump   = $writer->getDump($charGuid);   // null = character is deleted
 */
class CharacterDumpWriter
{
    /** @var \Doctrine\DBAL\Connection */
    private $conn;

    private array $items = [];
    private array $mails = [];
    private array $pets  = [];

    private int $race = 0;

    private int $fakeGuid    = 0;
    private int $fakeAccount = 0;

    /**
     * Per-table mapping of which column holds the character GUID.
     * pet_aura / pet_spell / pet_spell_cooldown use `guid` for the PET id — excluded.
     */
    private const CHAR_GUID_COLUMN = [
        'characters'                     => 'guid',
        'character_account_data'         => 'guid',
        'character_achievement'          => 'guid',
        'character_achievement_progress' => 'guid',
        'character_action'               => 'guid',
        'character_aura'                 => 'guid',
        'character_equipmentsets'        => 'guid',
        'character_glyphs'               => 'guid',
        'character_homebind'             => 'guid',
        'character_inventory'            => 'guid',
        'character_pet'                  => 'owner',
        'character_queststatus'          => 'guid',
        'character_queststatus_daily'    => 'guid',
        'character_queststatus_weekly'   => 'guid',
        'character_queststatus_monthly'  => 'guid',
        'character_queststatus_seasonal' => 'guid',
        'character_queststatus_rewarded' => 'guid',
        'character_reputation'           => 'guid',
        'character_skills'               => 'guid',
        'character_spell'                => 'guid',
        'character_spell_cooldown'       => 'guid',
        'character_talent'               => 'guid',
        'mail'                           => 'receiver',
        'mail_items'                     => 'receiver',
        'item_instance'                  => 'owner_guid',
        'character_gifts'                => 'guid',
    ];

    // Alliance races in WotLK: Human(1), Dwarf(3), NightElf(4), Gnome(7), Draenei(11)
    private const ALLIANCE_RACES = [1, 3, 4, 7, 11];

    // Stormwind — Trade District
    private const POS_STORMWIND = [
        'map'         => 0,
        'zone'        => 1519,
        'position_x'  => -8865.09,
        'position_y'  => 671.793,
        'position_z'  => 97.9034,
        'orientation' => 2.16098,
    ];

    // Neutral fallback — Booty Bay
    private const POS_BOOTY_BAY = [
        'map'         => 0,
        'zone'        => 33,
        'position_x'  => -14468.104,
        'position_y'  => 483.00665,
        'position_z'  => 26.776731,
        'orientation' => 0.0,
    ];

    // Orgrimmar — Valley of Strength
    private const POS_ORGRIMMAR = [
        'map'         => 1,
        'zone'        => 1637,
        'position_x'  => 1633.8,
        'position_y'  => -4440.47,
        'position_z'  => 15.634,
        'orientation' => 3.08343,
    ];

    private const SKIP_TABLES = [
        'character_declinedname',
        'character_pet_declinedname',
    ];

    /**
     * Table definitions — must stay in this exact order (matches DumpTables[]).
     *
     * 'where' : column used in the WHERE clause
     * 'set'   : which pre-collected ID set to use (null = use char $guid directly)
     */
    private const DUMP_TABLES = [
        ['table' => 'characters',                     'where' => 'guid',      'set' => null    ],
        ['table' => 'character_account_data',         'where' => 'guid',      'set' => null    ],
        ['table' => 'character_achievement',          'where' => 'guid',      'set' => null    ],
        ['table' => 'character_achievement_progress', 'where' => 'guid',      'set' => null    ],
        ['table' => 'character_action',               'where' => 'guid',      'set' => null    ],
        ['table' => 'character_aura',                 'where' => 'guid',      'set' => null    ],
        ['table' => 'character_declinedname',         'where' => 'guid',      'set' => null    ],
        ['table' => 'character_equipmentsets',        'where' => 'guid',      'set' => null    ],
        ['table' => 'character_glyphs',               'where' => 'guid',      'set' => null    ],
        ['table' => 'character_homebind',             'where' => 'guid',      'set' => null    ],
        ['table' => 'character_inventory',            'where' => 'guid',      'set' => null    ],
        ['table' => 'character_pet',                  'where' => 'owner',     'set' => null    ],
        ['table' => 'character_pet_declinedname',     'where' => 'owner',     'set' => null    ],
        ['table' => 'character_queststatus',          'where' => 'guid',      'set' => null    ],
        ['table' => 'character_queststatus_daily',    'where' => 'guid',      'set' => null    ],
        ['table' => 'character_queststatus_weekly',   'where' => 'guid',      'set' => null    ],
        ['table' => 'character_queststatus_monthly',  'where' => 'guid',      'set' => null    ],
        ['table' => 'character_queststatus_seasonal', 'where' => 'guid',      'set' => null    ],
        ['table' => 'character_queststatus_rewarded', 'where' => 'guid',      'set' => null    ],
        ['table' => 'character_reputation',           'where' => 'guid',      'set' => null    ],
        ['table' => 'character_skills',               'where' => 'guid',      'set' => null    ],
        ['table' => 'character_spell',                'where' => 'guid',      'set' => null    ],
        ['table' => 'character_spell_cooldown',       'where' => 'guid',      'set' => null    ],
        ['table' => 'character_talent',               'where' => 'guid',      'set' => null    ],
        ['table' => 'mail',                           'where' => 'receiver',  'set' => null    ],
        ['table' => 'mail_items',                     'where' => 'mail_id',   'set' => 'mails' ],
        ['table' => 'pet_aura',                       'where' => 'guid',      'set' => 'pets'  ],
        ['table' => 'pet_spell',                      'where' => 'guid',      'set' => 'pets'  ],
        ['table' => 'pet_spell_cooldown',             'where' => 'guid',      'set' => 'pets'  ],
        ['table' => 'item_instance',                  'where' => 'guid',      'set' => 'items' ],
        ['table' => 'character_gifts',                'where' => 'item_guid', 'set' => 'items' ],
    ];

    public function __construct($conn)
    {
        $this->conn = $conn;
    }

    /**
     * Generate a PII-stripped pdump string for the given character GUID.
     *
     * Returns null if the character is flagged as deleted
     * (deleteInfos_Account is non-null) — mirroring the C++ DUMP_CHARACTER_DELETED check.
     */
    public function getDump(int $guid): ?string
    {
        $this->items       = [];
        $this->mails       = [];
        $this->pets        = [];
        $this->race        = 0;
        // Use the upper quarter of INT UNSIGNED (max 4,294,967,295) —
        // real servers are extremely unlikely to have GUIDs or account IDs this high.
        $this->fakeGuid    = random_int(3_000_000_000, 4_294_967_290);
        $this->fakeAccount = random_int(3_000_000_000, 4_294_967_290);

        $charRow = $this->conn
            ->executeQuery(
                "SELECT `deleteInfos_Account`, `race` FROM `characters` WHERE `guid` = ?",
                [$guid]
            )
            ->fetchAssociative();

        if (!$charRow || $charRow['deleteInfos_Account'] !== null) {
            return null;
        }

        $this->race = (int) $charRow['race'];

        $this->populateGuids($guid);

        $lines = [];
        foreach (self::DUMP_TABLES as $def) {
            if (in_array($def['table'], self::SKIP_TABLES, true)) {
                continue;
            }

            $tableLines = $this->dumpTable($guid, $def);
            if ($tableLines === null) {
                return null;
            }
            foreach ($tableLines as $line) {
                $lines[] = $line;
            }
        }

        $eol     = "\r\n";
        $header  = "IMPORTANT NOTE: THIS DUMPFILE IS MADE FOR USE WITH THE 'PDUMP' COMMAND ONLY - EITHER THROUGH INGAME CHAT OR ON CONSOLE!" . $eol;
        $header .= "IMPORTANT NOTE: DO NOT apply it directly - it will irreversibly DAMAGE and CORRUPT your database! You have been warned!" . $eol;
        $header .= $eol;

        return $header . implode($eol, $lines) . (count($lines) ? $eol : '');
    }

    private function isAlliance(): bool
    {
        return in_array($this->race, self::ALLIANCE_RACES, true);
    }

    private function capitalPos(): array
    {
        if ($this->race === 0) {
            return self::POS_BOOTY_BAY;
        }
        return $this->isAlliance() ? self::POS_STORMWIND : self::POS_ORGRIMMAR;
    }

    /**
     * Collect secondary IDs (pets, mails, items) — mirrors PopulateGuids().
     */
    private function populateGuids(int $guid): void
    {
        $rs = $this->conn->executeQuery(
            "SELECT `id` FROM `character_pet` WHERE `owner` = ?", [$guid]
        );
        while ($id = $rs->fetchOne()) {
            $this->pets[] = (int) $id;
        }

        $rs = $this->conn->executeQuery(
            "SELECT `id` FROM `mail` WHERE `receiver` = ?", [$guid]
        );
        while ($id = $rs->fetchOne()) {
            $this->mails[] = (int) $id;
        }

        $rs = $this->conn->executeQuery(
            "SELECT `guid` FROM `item_instance` WHERE `owner_guid` = ?", [$guid]
        );
        while ($id = $rs->fetchOne()) {
            $this->items[] = (int) $id;
        }
    }

    /**
     * Dump one table, returning an array of INSERT lines (or [] if no rows).
     *
     * @return string[]|null
     */
    private function dumpTable(int $guid, array $def): ?array
    {
        $table      = $def['table'];
        $whereField = $def['where'];
        $setName    = $def['set'];

        if ($setName !== null) {
            $ids = $this->$setName;
            if (empty($ids)) {
                return [];
            }
            $placeholders = implode(', ', array_fill(0, count($ids), '?'));
            $sql    = "SELECT * FROM `{$table}` WHERE `{$whereField}` IN ({$placeholders})";
            $params = $ids;
        } else {
            $sql    = "SELECT * FROM `{$table}` WHERE `{$whereField}` = ?";
            $params = [$guid];
        }

        $rs = $this->conn->executeQuery($sql, $params);

        $lines       = [];
        $columnNames = [];
        while ($row = $rs->fetchAssociative()) {
            if (empty($columnNames)) {
                $columnNames = array_keys($row);
            }
            $row = $this->stripPii($table, $row);
            $lines[] = $this->buildInsert($table, $columnNames, $row);
        }

        return $lines;
    }

    /**
     * Strip / sanitise PII fields from a row before it is serialised.
     * Returns the modified row.
     */
    private function stripPii(string $table, array $row): array
    {
        $cap = $this->capitalPos();

        switch ($table) {
            case 'characters':
                $row['name']  = 'Unknown';
                $row['money'] = '0';
                $row['logout_time']          = '0';
                $row['totaltime']            = '0';
                $row['leveltime']            = '0';
                $row['latency']              = '0';
                $row['online']               = '0';
                $row['creation_date']        = '2000-01-01 00:00:00';
                $row['death_expire_time']    = '0';
                $row['rest_bonus']           = '0';
                $row['is_logout_resting']    = '0';
                $row['todayHonorPoints']     = '0';
                $row['yesterdayHonorPoints'] = '0';
                $row['todayKills']           = '0';
                $row['yesterdayKills']       = '0';
                $row['taxi_path']            = null;
                $row['innTriggerId']         = '0';
                $row['trans_x']   = '0';
                $row['trans_y']   = '0';
                $row['trans_z']   = '0';
                $row['trans_o']   = '0';
                $row['transguid'] = '0';
                $row['map']          = (string) $cap['map'];
                $row['zone']         = (string) $cap['zone'];
                $row['position_x']   = (string) $cap['position_x'];
                $row['position_y']   = (string) $cap['position_y'];
                $row['position_z']   = (string) $cap['position_z'];
                $row['orientation']  = (string) $cap['orientation'];
                $row['instance_id']  = '0';
                $row['instance_mode_mask'] = '0';
                break;

            case 'character_homebind':
                $row['mapId']  = (string) $cap['map'];
                $row['zoneId'] = (string) $cap['zone'];
                $row['posX']   = (string) $cap['position_x'];
                $row['posY']   = (string) $cap['position_y'];
                $row['posZ']   = (string) $cap['position_z'];
                break;

            case 'character_account_data':
                $row['time'] = '0';
                // Strip custom channel names from the type-7 chat layout blob.
                // Keep only Blizzard's built-in channels; player-named channels
                // (e.g. guild recruitment, custom group channels) can be PII.
                if ((int)($row['type'] ?? -1) === 7 && !empty($row['data'])) {
                    $row['data'] = self::stripCustomChannels($row['data']);
                }
                break;

            case 'character_aura':
                if (isset($row['caster_guid'])) $row['caster_guid'] = '0';
                break;

            case 'character_equipmentsets':
                $row['name'] = '';
                break;

            case 'character_achievement':
            case 'character_achievement_progress':
                $row['date'] = '0';
                break;

            case 'item_instance':
                $row['playedTime']      = '0';
                $row['text']            = null;
                $row['creatorGuid']     = '0';
                $row['giftCreatorGuid'] = '0';
                break;

            case 'mail':
                $row['subject']      = 'Redacted';
                $row['body']         = 'Redacted';
                $row['sender']       = '0';
                $row['expire_time']  = '0';
                $row['deliver_time'] = '0';
                break;

            case 'character_pet':
                $row['name'] = null;
                break;
        }

        // Replace real char GUID with anonymised value, using the correct column per table
        if (isset(self::CHAR_GUID_COLUMN[$table])) {
            $col       = self::CHAR_GUID_COLUMN[$table];
            $row[$col] = (string) $this->fakeGuid;
        }

        // Replace real account ID (only present in the characters row)
        if ($table === 'characters') {
            $row['account'] = (string) $this->fakeAccount;
        }

        return $row;
    }

    /**
     * Blizzard built-in channel names that are safe to keep.
     * Anything not in this list inside a CHANNELS...END block is player-defined.
     */
    private const DEFAULT_CHANNELS = [
        'General', 'Trade', 'LocalDefense', 'LookingForGroup',
        'GuildRecruitment', 'WorldDefense',
    ];

    /**
     * Remove player-defined channel names from the type-7 chat config blob.
     *
     * The blob uses literal \n characters between lines (it's stored escaped
     * in MySQL). We decode, strip, then re-encode back.
     *
     * CHANNELS blocks look like:
     *   CHANNELS\n
     *   SomeChannel\n
     *   AnotherChannel\n
     *   END\n
     */
    private static function stripCustomChannels(string $data): string
    {
        $decoded = preg_replace_callback(
            '/^CHANNELS\n(.*?\n)END\n/ms',
            function (array $m): string {
                $kept = '';
                foreach (explode("\n", rtrim($m[1], "\n")) as $line) {
                    $name = trim($line);
                    if ($name === '' || in_array($name, self::DEFAULT_CHANNELS, true)) {
                        $kept .= $name !== '' ? $name . "\n" : '';
                    }
                }
                return "CHANNELS\n{$kept}END\n";
            },
            $data
        );

        return $decoded ?? $data;
    }

    /**
     * Build a single INSERT line exactly as AppendTableDump() does in C++.
     */
    private function buildInsert(string $table, array $columns, array $row): string
    {
        $colList = implode('`, `', $columns);

        $values = [];
        foreach ($columns as $col) {
            $val = $row[$col] ?? null;
            $values[] = self::escapeValue($val);
        }

        return "INSERT INTO `{$table}` (`{$colList}`) VALUES (" . implode(', ', $values) . ");";
    }

    /**
     * Escape a field value the same way AzerothCore's EscapeString() does.
     */
    private static function escapeValue($val): string
    {
        if ($val === null || $val === '') {
            return "'NULL'";
        }

        $s = (string) $val;

        $s = str_replace('\\',   '\\\\', $s);
        $s = str_replace("\0",   '\\0',  $s);
        $s = str_replace("\n",   '\\n',  $s);
        $s = str_replace("\r",   '\\r',  $s);
        $s = str_replace("'",    "\\'",  $s);
        $s = str_replace('"',    '\\"',  $s);
        $s = str_replace("\x1a", '\\Z',  $s);

        return "'" . $s . "'";
    }
}
