<?php

namespace ACore\Components\ServerInfo;

use ACore\Manager\ACoreServices;
use ACore\Manager\Opts;

/**
 * In-game 2FA keys generated by the website instead of by `.account 2fa setup`.
 *
 * The core keeps the key it suggests in worldserver memory only (a static map in
 * cs_account.cpp), so a key shown here can never be confirmed with the in-game
 * command - the website has to write `account.totp_secret` itself. authserver
 * reads that column back through AEDecrypt<AES> (AuthSession.cpp), so the stored
 * blob has to match byte for byte what the core writes:
 *
 *   AES-128-GCM(secret) . iv(12) . tag(12)
 *
 * keyed by TOTPMasterSecret, which therefore has to be configured here too.
 */
class IngameTotp {

    /** Matches Acore::Crypto::TOTP::RECOMMENDED_SECRET_LENGTH. */
    const SECRET_BYTES = 20;

    const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

    /**
     * The 16 AES key bytes derived from the configured TOTPMasterSecret, or null
     * when it is unset or not a hexadecimal integer.
     *
     * SecretMgr parses the config value as a BigNumber capped to 128 bits and
     * hands AES `ToByteArray<16>()`, which is little-endian - hence the reverse.
     */
    public static function masterKey(): ?string {
        $hex = trim((string) Opts::I()->acore_totp_master_secret);
        if ($hex === '' || !preg_match('/^[0-9a-fA-F]+$/', $hex)) return null;

        $hex = substr(str_pad($hex, 32, '0', STR_PAD_LEFT), -32);
        $be  = hex2bin($hex);
        return $be === false ? null : strrev($be);
    }

    public static function isConfigured(): bool {
        return self::masterKey() !== null && function_exists('openssl_encrypt');
    }

    private static function pendingKey(int $userId): string {
        return 'acore_ingame_2fa_pending_' . $userId;
    }

    /**
     * The Base32 key currently offered to this user, generating one on first use.
     * It is kept only until the user confirms a code from it.
     */
    public static function pendingSecret(int $userId): string {
        $stored = self::peekPendingSecret($userId);
        if ($stored !== '') return $stored;

        $secret = self::base32Encode(random_bytes(self::SECRET_BYTES));
        set_transient(self::pendingKey($userId), $secret, DAY_IN_SECONDS);
        return $secret;
    }

    /** Like pendingSecret(), but never generates a new key. */
    public static function peekPendingSecret(int $userId): string {
        $stored = get_transient(self::pendingKey($userId));
        return (is_string($stored) && preg_match('/^[A-Z2-7]{32}$/', $stored)) ? $stored : '';
    }

    public static function forgetPendingSecret(int $userId): void {
        delete_transient(self::pendingKey($userId));
    }

    /**
     * Write the key to the account, encrypted the way the core expects.
     * Returns false when 2FA is already set up, so a stale form cannot overwrite
     * a key the user is depending on.
     */
    public static function activate(int $accountId, string $base32Secret): bool {
        $key = self::masterKey();
        if ($key === null) return false;

        $iv  = random_bytes(12);
        $tag = '';
        $ct  = openssl_encrypt(self::base32Decode($base32Secret), 'aes-128-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag, '', 12);
        if ($ct === false) return false;

        $conn = ACoreServices::I()->getAccountEm()->getConnection();
        $rows = $conn->executeStatement(
            'UPDATE account SET totp_secret = UNHEX(?) WHERE id = ? AND totp_secret IS NULL',
            [bin2hex($ct . $iv . $tag), $accountId]
        );
        return $rows === 1;
    }

    /**
     * The key the account is currently using, as Base32, or '' when it cannot be
     * read. The core encrypts it only when TOTPMasterSecret is set on its side
     * (cs_account.cpp), and a bare secret is the only one short enough to have no
     * IV and tag after it, so its length tells the two apart.
     *
     * Reading it lets the site check an in-game code without ever needing the
     * website's own 2FA.
     */
    public static function currentSecret(int $accountId): string {
        try {
            $conn = ACoreServices::I()->getAccountEm()->getConnection();
            $row  = $conn->executeQuery('SELECT HEX(totp_secret) AS secret FROM account WHERE id = ?', [$accountId])->fetchAssociative();
        } catch (\Throwable $e) {
            return '';
        }
        if (!$row || empty($row['secret'])) return '';

        $blob = (string) hex2bin($row['secret']);
        if (strlen($blob) === self::SECRET_BYTES) return self::base32Encode($blob);

        $key = self::masterKey();
        if ($key === null || strlen($blob) <= 24) return '';

        $raw = openssl_decrypt(
            substr($blob, 0, -24), 'aes-128-gcm', $key, OPENSSL_RAW_DATA,
            substr($blob, -24, 12), substr($blob, -12)
        );
        return $raw === false ? '' : self::base32Encode($raw);
    }

    /**
     * The otpauth:// URI behind the QR code. The site name is decoded because the
     * app should show "Ben & Co", not the entity-encoded form WordPress stores.
     */
    public static function otpauthUri(string $accountName, string $base32Secret): string {
        $issuer = trim(wp_specialchars_decode(get_bloginfo('name'), ENT_QUOTES));
        if ($issuer === '') $issuer = 'AzerothCore';

        return 'otpauth://totp/' . rawurlencode($issuer) . ':' . rawurlencode($accountName)
             . '?secret=' . $base32Secret
             . '&issuer=' . rawurlencode($issuer)
             . '&algorithm=SHA1&digits=6&period=30';
    }

    public static function base32Encode(string $bytes): string {
        $bits = '';
        foreach (str_split($bytes) as $byte) {
            $bits .= str_pad(decbin(ord($byte)), 8, '0', STR_PAD_LEFT);
        }
        $out = '';
        foreach (str_split($bits, 5) as $chunk) {
            $out .= self::BASE32_ALPHABET[bindec(str_pad($chunk, 5, '0', STR_PAD_RIGHT))];
        }
        return $out;
    }

    public static function base32Decode(string $base32): string {
        $bits = '';
        foreach (str_split(strtoupper(rtrim($base32, '='))) as $char) {
            $pos = strpos(self::BASE32_ALPHABET, $char);
            if ($pos === false) continue;
            $bits .= str_pad(decbin($pos), 5, '0', STR_PAD_LEFT);
        }
        $out = '';
        foreach (str_split($bits, 8) as $chunk) {
            if (strlen($chunk) < 8) break;
            $out .= chr(bindec($chunk));
        }
        return $out;
    }
}
