name: "Sync subtrees"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: drassil/action-git-subtree@main
        with:
          pat: ${{ secrets.PUSH_TOKEN }}
          repo: https://github.com/azerothcore/acore-cms-wp-plugin.git
          action: push
          prefix: src/acore-wp-plugin
          squash: false
